source "https://rubygems.org"
ruby "3.4.5"

group :development do
  gem "ruby-lsp"
end

# CocoaPods pinned
gem "cocoapods", "~> 1.16"

# Ruby 3.4 requires this stdlib as a separate gem for some deps
gem "base64"
