# # Resolve react_native_pods.rb with node to allow for hoisting
# require Pod::Executable.execute_command('node', ['-p',
#   'require.resolve(
#     "react-native/scripts/react_native_pods.rb",
#     {paths: [process.argv[1]]},
#   )', __dir__]).strip

# platform :ios, min_ios_version_supported
# prepare_react_native_project!



# linkage = ENV['USE_FRAMEWORKS']
# if linkage != nil
#   Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
#   use_frameworks! :linkage => linkage.to_sym
# end

# target 'client' do
#   config = use_native_modules!

#   use_react_native!(
#     :path => config[:reactNativePath],

#     # An absolute path to your application root.
#     :app_path => "#{Pod::Config.instance.installation_root}/.."
#   )

#   target 'clientTests' do
#     inherit! :complete
#     # Pods for testing
#   end

#   # post_install do |installer|
#   #   # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
#   #   react_native_post_install(
#   #     installer,
#   #     config[:reactNativePath],
#   #     :mac_catalyst_enabled => false
#   #   )
#   # end
#   post_install do |installer|
#     installer.pods_project.targets.each do |target|
#       if target.name == 'BoringSSL-GRPC'
#         target.source_build_phase.files.each do |file|
#           if file.settings && file.settings['COMPILER_FLAGS']
#             flags = file.settings['COMPILER_FLAGS'].split
#             flags.reject! { |flag| flag == '-GCC_WARN_INHIBIT_ALL_WARNINGS' }
#             file.settings['COMPILER_FLAGS'] = flags.join(' ')
#           end
#         end
#       end
#       target.build_configurations.each do |config|
#         config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.4'
#       end
#     end

#     # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
#     react_native_post_install(
#       installer,
#       config[:reactNativePath],
#       :mac_catalyst_enabled => false,
#       # :ccache_enabled => true
#     )
#   end
# end

# Start 2
# Resolve react_native_pods.rb with node to allow for hoisting
# require Pod::Executable.execute_command('node', ['-p',
#   'require.resolve(
#     "react-native/scripts/react_native_pods.rb",
#     {paths: [process.argv[1]]},
#   )', __dir__]).strip

# # 🔒 Force global min iOS early
# platform :ios, '15.1'
# ENV['IPHONEOS_DEPLOYMENT_TARGET'] = '15.1'

# prepare_react_native_project!

# # Only enable frameworks if you *must* (can complicate JSI libs)
# linkage = ENV['USE_FRAMEWORKS']
# if linkage
#   Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
#   use_frameworks! :linkage => linkage.to_sym
# end

# target 'client' do
#   config = use_native_modules!

#   # use_react_native!(
#   #   :path => config[:reactNativePath],
#   #   :app_path => "#{Pod::Config.instance.installation_root}/.."
#   #   # Hermes is default in RN 0.80
#   # )
#   use_react_native!(
#   :path => config[:reactNativePath],
#   :app_path => "#{Pod::Config.instance.installation_root}/..",
#   :new_arch_enabled => false
# )


#   target 'clientTests' do
#     inherit! :complete
#   end

#   post_install do |installer|
#     # Force ALL pods + configurations to iOS 15.1
#     installer.pods_project.targets.each do |t|
#       t.build_configurations.each do |cfg|
#         cfg.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.1'
#       end
#     end

#     # Also set the Pods project-level configs
#     installer.pods_project.build_configurations.each do |cfg|
#       cfg.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.1'
#     end

#     react_native_post_install(
#       installer,
#       config[:reactNativePath],
#       :mac_catalyst_enabled => false
#     )
#   end
# end


# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '15.1'
ENV['IPHONEOS_DEPLOYMENT_TARGET'] = '15.1'

prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'client' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :new_arch_enabled => false
  )

  target 'clientTests' do
    inherit! :complete
  end

  post_install do |installer|
    # Force ALL pods + configurations to iOS 15.1 and disable Folly coroutines
    installer.pods_project.targets.each do |t|
      t.build_configurations.each do |cfg|
        cfg.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.1'

        # Ensure arrays exist
        cfg.build_settings['OTHER_CPLUSPLUSFLAGS'] ||= ['$(inherited)']
        cfg.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']

        # Disable Folly coroutines everywhere
        cfg.build_settings['OTHER_CPLUSPLUSFLAGS'] << '-DFOLLY_HAS_COROUTINES=0'
        cfg.build_settings['OTHER_CPLUSPLUSFLAGS'] << '-DFOLLY_CFG_NO_COROUTINES=1'
        cfg.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'FOLLY_HAS_COROUTINES=0'
        cfg.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'FOLLY_CFG_NO_COROUTINES=1'

        # Keep C++20 (RN 0.80 expects it)
        cfg.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++20'
      end
    end

    # Also set the Pods project-level configs
    installer.pods_project.build_configurations.each do |cfg|
      cfg.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.1'
    end

    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end
