package com.client

import android.app.Application
import com.facebook.react.PackageList
import com.facebook.react.ReactApplication
import com.facebook.react.ReactHost
import com.facebook.react.ReactNativeApplicationEntryPoint.loadReactNative
import com.facebook.react.ReactNativeHost
import com.facebook.react.ReactPackage
import com.facebook.react.defaults.DefaultReactHost.getDefaultReactHost
import com.facebook.react.defaults.DefaultReactNativeHost

class MainApplication : Application(), ReactApplication {

  override val reactNativeHost: ReactNativeHost =
      object : DefaultReactNativeHost(this) {
        override fun getPackages(): List<ReactPackage> =
            PackageList(this).packages.apply {
              // Packages that cannot be autolinked yet can be added manually here, for example:
              // add(MyReactNativePackage())
            }

        override fun getJSMainModuleName(): String = "index"

        override fun getUseDeveloperSupport(): Boolean = BuildConfig.DEBUG

        override val isNewArchEnabled: Boolean = BuildConfig.IS_NEW_ARCHITECTURE_ENABLED
        override val isHermesEnabled: Boolean = BuildConfig.IS_HERMES_ENABLED
      }

  override val reactHost: ReactHost
    get() = getDefaultReactHost(applicationContext, reactNativeHost)

  override fun onCreate() {
    super.onCreate()
    loadReactNative(this)
  }
}



// package com.client

// import android.app.Application
// import com.facebook.react.PackageList
// import com.facebook.react.ReactApplication
// import com.facebook.react.ReactNativeHost
// import com.facebook.react.ReactPackage
// import com.facebook.react.defaults.DefaultNewArchitectureEntryPoint.load
// import com.facebook.react.defaults.DefaultReactNativeHost
// import com.facebook.soloader.SoLoader

// class MainApplication : Application(), ReactApplication {

//   override val reactNativeHost: ReactNativeHost = object : DefaultReactNativeHost(this) {
//     override fun getUseDeveloperSupport(): Boolean = BuildConfig.DEBUG

//     override fun getPackages(): MutableList<ReactPackage> =
//       PackageList(this).packages.apply {
//         // Add your own packages here if you have any:
//         // add(MyCustomPackage())
//       }

//     override fun getJSMainModuleName(): String = "index"

//     // These BuildConfig flags are generated by the RN Gradle plugin
//     override fun isNewArchEnabled(): Boolean = BuildConfig.IS_NEW_ARCHITECTURE_ENABLED
//     override fun isHermesEnabled(): Boolean = BuildConfig.IS_HERMES_ENABLED
//   }

//   override fun onCreate() {
//     super.onCreate()
//     SoLoader.init(this, false)
//     if (BuildConfig.IS_NEW_ARCHITECTURE_ENABLED) {
//       load()
//     }
//   }
// }


// package com.client

// import android.app.Application
// import com.facebook.react.PackageList
// import com.facebook.react.ReactApplication
// import com.facebook.react.ReactNativeHost
// import com.facebook.react.ReactPackage
// import com.facebook.react.defaults.DefaultNewArchitectureEntryPoint.load
// import com.facebook.react.defaults.DefaultReactNativeHost


// class MainApplication : Application(), ReactApplication {

//   override val reactNativeHost: ReactNativeHost =
//     object : DefaultReactNativeHost(this) {
//       override fun getPackages(): List<ReactPackage> =
//         PackageList(this).packages

//       override fun getJSMainModuleName(): String = "index"

//       override fun getUseDeveloperSupport(): Boolean = BuildConfig.DEBUG

//       // NOTE: Do NOT override isHermesEnabled / isNewArchEnabled on RN 0.80+.
//       // They’re controlled by gradle.properties (hermesEnabled/newArchEnabled).
//     }

//   override fun onCreate() {
//     super.onCreate()
//     SoLoader.init(this, /* native exopackage */ false)

//     // Optional: still fine to guard the new arch entrypoint with BuildConfig:
//     if (BuildConfig.IS_NEW_ARCHITECTURE_ENABLED) {
//       load()
//     }
//   }
// }

